version: "3.9"
services:
  postgres:
    restart: always
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=restaurant
      - POSTGRES_USER=restaurant
      - POSTGRES_DB=restaurant
    volumes:
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/data/postgres
    ports:
      - '5432:5432'

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=restaurant@stringconcat.com
      - PGADMIN_DEFAULT_PASSWORD=restaurant
    depends_on:
      - postgres
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo '*:5432:restaurant:restaurant:restaurant' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker/servers.json:/pgadmin4/servers.json
    ports:
      - "15432:80"

  rabbitmq:
      restart: always
      image: rabbitmq:3.9.11
      environment:
        - RABBITMQ_DEFAULT_USER=rabbitmq
        - RABBITMQ_DEFAULT_PASS=rabbitmq
      ports:
        - "5672:5672"


  kitchen:
    restart: always
    image: restaurant/kitchen:latest
    ports:
      - '8080:8080'

  shop:
    restart: always
    image: restaurant/shop:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/restaurant
      - SPRING_DATASOURCE_USERNAME=restaurant
      - SPRING_DATASOURCE_PASSWORD=restaurant
    depends_on:
      - postgres
    ports:
      - '2121:2121'
      - '8081:8081'

  mock-server:
    restart: always
    image: restaurant/mock-server:latest
    ports:
      - '8091:8091'

  portainer:
    restart: always
    image: portainer/portainer
    ports:
      - '9000:9000'
    command: -H unix:///var/run/docker.sock --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
  postgres:
  pgadmin: